### ISSUE TITLE
glicko2 infinite loop

### ISSUE THREAD

**Issue by llimllib** [sublee/glicko#1]
Thanks so much for this library, it's been super useful to me already.

I've been hitting an infinite loop in `determine_volatility` that I'm having trouble debugging. I've posted a [gist](https://gist.github.com/llimllib/8acf036fb6e1d343e409) containing all the files necessary to recreate it.

I've been trying to whittle it down into a smaller bug report, but unfortunately it requires all the data files I've put in the gist; if you remove any of them the bug doesn't manifest itself. 

I have been trying to reproduce the bug by calling the function with the same arguments that I see it lock up on, but I've been unable to get it to happen that way.

I hope that if you download that gist and run it, you'll be able to reproduce the problem.

I'll keep working on it in the meantime.

**Comment by llimllib** [comment]
Ha! I've managed to get it down to three lines, I wasn't printing the arguments with great enough precision.

```
import glicko
g = glicko.Glicko2(volatility=0.76)
g.determine_volatility(g.create_rating(-3.5744344457376810986204418441047892,1.61207698271845467630214443488512188,1.09021015118913666697153530549257994),19.070260525665084117008518660441041,25.990744829894950385096308309584856)
```

I've updated the gist accordingly

**Comment by llimllib** [comment]
Actually, you don't even need to set a volatility, the bug manifests even with a default glicko environment.

**Comment by sublee** [comment]
Thanks to report!

**Comment by llimllib** [comment]
Thanks for the quick fix!
